<a href="https://colab.research.google.com/github/francomanca93/fundamentos-practicos-de-machine-learning/blob/main/1.fundamentos-practicos/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Array de 1 dimension

In [2]:
np.array([10, 20, 5, 15, 50])

array([10, 20,  5, 15, 50])

Buscar valores e intervalos de valores en un array, sin necesidad de utilizar un for loop.

In [3]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [4]:
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [5]:
a[3:7]

array([ 4, 30, 51,  7])

Dame los valores que se encuentren se encuentre a partir de la posicion 1, vaya hasta el final "::" y que sea de 4 en 4.

In [6]:
a[1::4]

array([30, 51, 40])

Crear matrices de 0 y 1, de varias dimensiones.

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
ones = np.ones((4, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
type(ones)

numpy.ndarray

In [12]:
type(ones[3])

numpy.ndarray

Crear matrices con intervalos y limites:

np.linspace(limite inferior, limite superior, numero de valores)

In [14]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [30]:
b = np.array([['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

Sabe las dimensiones

In [17]:
b.ndim

2

Ordenando datos

In [18]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

Podemos asignar una cabecera a nuestros valores de la siguiente manera:

In [20]:
cabecera = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype = cabecera)

np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

Llenar un array de manera dinamica

In [21]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
np.arange(5, 30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
np.arange(5, 10, 5)

array([5])

In [24]:
np.full( (3, 5), 10 )

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [25]:
np.diag([0, 3, 9, 10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

Resumen:

- **np.zeros(<'dimension'>)** → crea un arreglo de dimensión indicada con todos los valores iguales a 0
- **np.ones(<'dimension'>)** → crea un arreglo de dimensión indicada con todos los valores iguales a 1
- **np.linspace(<'inicio'>,<'fin'>,<'n_datos'>)** → crea un arreglo de n datos igualmente espaciados con un inicio y fin indicados
- **<'arreglo'>.ndim** → devuelve la dimensión del arreglo
- **np.sort(arreglo)** → devuelve el arreglo ordenado (en caso de tener encabezado se puede usar el atributo order=’<'nombre_dato'>’)
- **np.arrange(<'inicio'>,<'fin'>,<'pasos'>)** → crea un arreglo con inicio y fin dado aumentando el paso
- **np.full(<'dimension'>,<'valores'>)** → crea un arreglo de la dimensión data cuyos componentes son llenados con los valores
- **np.diag(<'diagonal'>,<'k'>)** → crea una matriz diagonal con los valores dados (k es opcional y determina el número de columnas (signo negativo) o filas(signo positivo) a aumentar en caso de que la matriz no sea cuadrada)
